Advanced Software Engineering/Lab3_51900690/Lab3_51900690/Models/ErrorViewModel.cs
using System;

namespace Lab3_51900690.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Advanced Software Engineering/Lab3_51900690/Lab3_51900690/Models/Laptop.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab3_51900690.Models
{
    public class Laptop
    {
        public string ID {  get; set; }
        public string name {  get; set; }
        public int price {  get; set; }
        public string cpu {  get; set; }
        public int ram {  get; set; }
        public int storage {  get; set; }
    }
}

Advanced Software Engineering/Lab3_51900690/Lab3_51900690/Controllers/HomeController.cs
using Lab3_51900690.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Lab3_51900690.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Advanced Software Engineering/Lab3_51900690/Lab3_51900690/Controllers/LaptopController.cs
using Lab3_51900690.Models;
using Lab3_51900690.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab3_51900690.Controllers
{
    public class LaptopController : Controller
    {
        // GET: HomeController1
        public ActionResult Index()
        {
            var lstLaptop = LaptopRes.GetAll();
            return View(lstLaptop);
        }

        // GET: HomeController1/Details/5
        public ActionResult Details(string ID)
        {
            if(ID == null)
            {
                return NotFound();
            }
            var laptop = LaptopRes.GetByID(ID);
            if(laptop == null)
            {
                return NotFound();
            }
            return View(laptop);
        }

        // GET: HomeController1/Create
        public ActionResult Create()
        {
            var laptop = new Laptop();
            return View(laptop);
        }

        // POST: HomeController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Laptop laptop)
        {
            if (ModelState.IsValid)
            {
                laptop = LaptopRes.InsertLaptop(laptop);
                return RedirectToAction(nameof(Index));
            }
            return View(laptop);
        }

        // GET: HomeController1/Edit/5
        public ActionResult Edit(string id)
        {
            if(id == null)
                return NotFound();
            var laptop = LaptopRes.GetByID(id);
            if(laptop == null)
                return NotFound();
            return View(laptop);
        }

        // POST: HomeController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, Laptop laptop)
        {
            if (id != laptop.ID)
                return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    laptop = LaptopRes.EditByIDs(laptop);
                }
                catch (Exception e)
                {
                    if (!LaptopExists(laptop.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        Console.WriteLine(e.Message);
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(laptop);
        }

        // GET: HomeController1/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
                return NotFound();
            var laptop = LaptopRes.GetByID(id);
            if (laptop == null)
                return NotFound();
            return View(laptop);
        }

        // POST: HomeController1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var laptop = LaptopRes.DeleteByID(id);
            return RedirectToAction(nameof(Index));
        }

        private bool LaptopExists(string id)
        {
            return false;
        }
    }
}

Advanced Software Engineering/Lab3_51900690/Lab3_51900690/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Advanced Software Engineering/Lab3_51900690/Lab3_51900690/Views/Laptop/Create.cshtml
@model Lab3_51900690.Models.Laptop

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Laptop</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cpu" class="control-label"></label>
                <input asp-for="cpu" class="form-control" />
                <span asp-validation-for="cpu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ram" class="control-label"></label>
                <input asp-for="ram" class="form-control" />
                <span asp-validation-for="ram" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="storage" class="control-label"></label>
                <input asp-for="storage" class="form-control" />
                <span asp-validation-for="storage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Advanced Software Engineering/Lab3_51900690/Lab3_51900690/Views/Laptop/Delete.cshtml
@model Lab3_51900690.Models.Laptop

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Laptop</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cpu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cpu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ram)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ram)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.storage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.storage)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Advanced Software Engineering/Lab3_51900690/Lab3_51900690/Views/Laptop/Details.cshtml
@model Lab3_51900690.Models.Laptop

<div>
    <h4>Laptop</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cpu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cpu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ram)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ram)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.storage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.storage)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Advanced Software Engineering/Lab3_51900690/Lab3_51900690/Views/Laptop/Edit.cshtml
@model Lab3_51900690.Models.Laptop

<h4>Laptop</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cpu" class="control-label"></label>
                <input asp-for="cpu" class="form-control" />
                <span asp-validation-for="cpu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ram" class="control-label"></label>
                <input asp-for="ram" class="form-control" />
                <span asp-validation-for="ram" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="storage" class="control-label"></label>
                <input asp-for="storage" class="form-control" />
                <span asp-validation-for="storage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Advanced Software Engineering/Lab3_51900690/Lab3_51900690/Views/Laptop/Index.cshtml
@model IEnumerable<Lab3_51900690.Models.Laptop>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cpu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ram)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.storage)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cpu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ram)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.storage)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
}
    </tbody>
</table>

Advanced Software Engineering/Lab3_51900690/Lab3_51900690/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab3_51900690</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab3_51900690</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Laptop" asp-action="Index">Laptop</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Lab3_51900690 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>